In [1]:
import numpy as np

In [6]:
#Function wherein the columns of the output matrixs are increasing power of their input vector

def inc_matrix(inpmatrix, n, increasingValue = False):
    if not increasingValue:
        output_matrix = np.array([x**(n-1-i) for x in inpmatrix for i in range(n)]).reshape(inpmatrix.size, n)
    elif increasingValue:
        output_matrix = np.array([x**i for x in inpmatrix for i in range(n)]).reshape(inpmatrix.size, n)
        
    return output_matrix

In [7]:
inputmatrix = np.array([1,2,3,4,5,6])
noofcols = 4
out_mat_desc = inc_matrix(inputmatrix,noofcols,False)
out_mat_asc = inc_matrix(inputmatrix,noofcols,True)

print("The input matrix is : ",inputmatrix,"\n")
print("The no of required colums are :",noofcols,"\n")
print("Matrix with decreasing orders of powers : \n\n",out_mat_desc, "\n")
print("Matrix with increasing orders of powers : \n\n",out_mat_asc, "\n")

The input matrix is :  [1 2 3 4 5 6] 

The no of required colums are : 4 

Matrix with decreasing orders of powers : 

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]] 

Matrix with increasing orders of powers : 

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]] 



Problem Statement

1.Given a sequence of n values x1,x2,...,xn and a window size k>0,the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values

In [20]:
def mov_avg(inp,k):
    str_len = len(inp)
    for i in range(0,str_len-k+1):
        sum = 0
        st = []
        for j in range(i,i+k):
            sum = sum + inp[j]
            st.append(str(inp[j]))
        avg = sum/k
        st1 = "+".join(st)
        st1 = "("+st1+")"
        st1=st1+"/"+str(k)
        print("y",(i+1), " "*(2),'%d'%avg,"=",st1)

In [21]:
input_array=np.array([10,20,30,40,50,60,70,80,90,100])
k=4
mov_avg(input_array,k)

y 1    25 = (10+20+30+40)/4
y 2    35 = (20+30+40+50)/4
y 3    45 = (30+40+50+60)/4
y 4    55 = (40+50+60+70)/4
y 5    65 = (50+60+70+80)/4
y 6    75 = (60+70+80+90)/4
y 7    85 = (70+80+90+100)/4


In [22]:
a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
mov_avg(a,k)

y 1    5 = (3+5+7)/3
y 2    4 = (5+7+2)/3
y 3    5 = (7+2+8)/3
y 4    6 = (2+8+10)/3
y 5    9 = (8+10+11)/3
y 6    28 = (10+11+65)/3
y 7    49 = (11+65+72)/3
y 8    72 = (65+72+81)/3
y 9    84 = (72+81+99)/3
y 10    93 = (81+99+100)/3
y 11    116 = (99+100+150)/3
